[package]
license = ["Apache-2.0"]
keywords = ["Commerce/eCommerce", "Cost/Paid", "Trigger"]
org = "ballerinax"
name = "trigger.shopify"
repository = "https://github.com/ballerina-platform/asyncapi-triggers"
version = "1.3.1"
distribution = "2201.11.0-20250127-101700-a4b67fe5"
icon = "docs/icon.png"
authors = ["Ballerina"]

[build-options]
observabilityIncluded = true
