[package]
license = ["Apache-2.0"]
keywords = ["Sales & CRM/Customer Relationship Management", "Cost/Freemium", "Trigger"]
org = "ballerinax"
name = "trigger.hubspot"
repository = "https://github.com/ballerina-platform/asyncapi-triggers"
version = "0.9.0"
distribution = "2201.11.0-20250127-101700-a4b67fe5"
icon = "docs/icon.png"
authors = ["Ballerina"]

[build-options]
observabilityIncluded = true
