[package]
license = ["Apache-2.0"]
keywords = ["Communication chat/voice", "Cost/Freemium" , "Vendor/Twilio"]
org = "ballerinax"
name = "trigger.twilio"
repository = "https://github.com/ballerina-platform/asyncapi-triggers"
version = "0.9.0"
icon = "docs/icon.png"
distribution = "2201.11.0-20250127-101700-a4b67fe5"
authors = ["Ballerina"]

[build-options]
observabilityIncluded = true
