[package]
license = ["Apache-2.0"]
keywords = ["Communication/Team Chat", "Cost/Freemium"]
org = "ballerinax"
name = "trigger.slack"
icon = "icon.png"
repository = "https://github.com/ballerina-platform/asyncapi-triggers"
<<<<<<< HEAD
version = "0.8.0"
distribution = "2201.11.0-20250127-101700-a4b67fe5"
=======
version = "0.9.0"
distribution = "2201.11.0"
>>>>>>> upstream/main
icon = "docs/icon.png"
authors = ["Ballerina"]

[build-options]
observabilityIncluded = true
